# Generated by Django 4.1.5 on 2023-01-14 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='cost',
            new_name='cover',
        ),
        migrations.AddField(
            model_name='policy',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
